language: r
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

github_packages:
  - hadley/testthat
  - hadley/dplyr
  - rstats-db/DBI
  
addons:
  apt_packages:
    - pandoc
